import React from "react";

export default function OGGalleryPage() {
  const variants = [
    { id: "1", name: "Classic Brutalist", description: "Bold typography with a professional subtitle ('For professionals...') and integrated logo on a deep black background." },
    { id: "2", name: "Elegant Minimalist", description: "Centered layout with a clean circle logo and spacious typography." },
    { id: "3", name: "Modern Editorial", description: "Side-by-side layout with large headline and clean logo on white background." },
  ];

  return (
    <div className="min-h-screen bg-black text-white p-12 font-sans">
      <header className="max-w-6xl mx-auto mb-16">
        <h1 className="text-5xl font-bold mb-4 tracking-tight">OG Image Variants</h1>
        <p className="text-xl text-zinc-400 max-w-2xl">
          Preview the dynamic Open Graph images generated by the Next.js Route Handler. 
          Choose the one that best fits our "Super Premium" aesthetic.
        </p>
      </header>

      <main className="max-w-6xl mx-auto space-y-24">
        {variants.map((variant) => (
          <section key={variant.id} className="space-y-6">
            <div className="flex items-baseline justify-between">
              <h2 className="text-3xl font-semibold">Variant {variant.id}: {variant.name}</h2>
              <code className="bg-zinc-900 px-3 py-1 rounded text-zinc-500">?variant={variant.id}</code>
            </div>
            <p className="text-zinc-400">{variant.description}</p>
            
            <div className="grid grid-cols-1 gap-8">
              <div className="space-y-4">
                <p className="text-sm uppercase tracking-widest text-zinc-600 font-bold">Standard Preview</p>
                <div className="border border-zinc-800 rounded-2xl overflow-hidden shadow-2xl">
                  <img 
                    src={`/api/og?variant=${variant.id}`} 
                    alt={variant.name} 
                    className="w-full aspect-[1200/630] object-cover"
                  />
                </div>
              </div>

              <div className="space-y-4">
                <p className="text-sm uppercase tracking-widest text-zinc-600 font-bold">Personalized Preview (?name=Adarsh)</p>
                <div className="border border-zinc-800 rounded-2xl overflow-hidden shadow-2xl">
                  <img 
                    src={`/api/og?variant=${variant.id}&name=Adarsh`} 
                    alt={`${variant.name} Personalized`} 
                    className="w-full aspect-[1200/630] object-cover"
                  />
                </div>
              </div>
            </div>
          </section>
        ))}
      </main>

      <footer className="max-w-6xl mx-auto mt-24 pt-12 border-t border-zinc-900 text-zinc-600 text-sm">
        Generated dynamically using Next.js ImageResponse.
      </footer>
    </div>
  );
}
